<a href="https://colab.research.google.com/github/mingzinote/orm/blob/main/0104__%EC%8B%9C%ED%80%80%EC%8A%A4%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 시퀀스 자료형
* example::: 예

In [ ]:
# 1.1 인덱싱
#01234
#    (-) 54321
example = 'abcde'
print(example[0])          # 출력: a
print(example[2])          # 출력: c
print(example[-1])         # 출력: e

a
c
e


In [ ]:
# 1.2 슬라이싱

example = 'abcde'
print(example[1:3])        # 출력: bc
print(example[-4:-2])                                 #>>> 몰라 ㅜㅜ
print(range(10)[3])        # 출력: 3                      #>>> 몰라 ㅜㅜ
print(range(100)[::5])     # 출력: range(0, 100, 5)       #>>> 몰라 ㅜㅜ

bc
bc
3
range(0, 100, 5)


In [ ]:
# 1.3 특정항목 포함 여부

example = 'abcde'
print('a' in example)      # 출력: True
print('z' in example)      # 출력: False

In [ ]:
# 1.4 연결 & 반복

example1 = 'abcde'
example2 = 'f'
print(example1 + example2) # 출력: abcdef
print(example2 * 3)        # 출력: fff

abcdef
fff


In [ ]:
# 내장함수를 사용!

example = 'abcde'
print(len(example))        # 출력: 5
print(min(example))        # 출력: a
print(max(example))        # 출력: e

5
a
e


# 2. 패킹과 언패킹
* **중요한 부분**이지만 헷갈리기 때문에 잘! 봐두자.

In [ ]:
# 2.1 튜플 패킹

packed_tuple = 1, 2, 3, 4
print(packed_tuple)        # 출력: (1, 2, 3, 4)
type(packed_tuple)

(1, 2, 3, 4)


tuple

In [ ]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)

# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)                    # 출력: 1
print(b)                    # 출력: 2

(1, 2, 3, 4)
1
2


In [ ]:
# 다양한 패킹 / 언패킹
# range는 0부터 n-1까지 숫자를 생성하는 함수

a, b, c = range(3)
print(range(3))
print(a, b, c)

range(0, 3)
0 1 2


In [ ]:
a, b, c, d, e = 'hello'
print(a, b, c, d, e)

h e l l o


In [ ]:
a, b = [10, 20]
print(a, b)
print(a + b)

10 20
30


* 언패킹은 시퀀스 자료형이라면 다 활용할 수 있다!

In [ ]:
total_sum = 0

for i in range(5):
    total_sum += i
    print(total_sum)

print(total_sum)

0
1
3
6
10
10


In [ ]:
# 별표 * 이용한 언패킹

first, *middle, last = [1, 2, 3, 4, 5]

print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


In [ ]:
first, *middle = [1, 2, 3, 4, 5]

print(first)
print(middle)

1
[2, 3, 4, 5]


In [ ]:
*middle, first = [1, 2, 3, 4, 5]

print(first)
print(middle)

5
[1, 2, 3, 4]


# 3. 리스트

In [ ]:
# 리스트의 장점: 여러가지 자료형을 넣을 수 있다.

z = [1, 'apple', 2.5, ['a', 'b'], (1, 2), True]
print(z)
print(z[0])
print(z[1])
print(z[2])
print(z[3])
print(z[4])
print(int(z[5]))

[1, 'apple', 2.5, ['a', 'b'], (1, 2), True]
1
apple
2.5
['a', 'b']
(1, 2)
1


In [ ]:
# 이렇게 적는것도 가능
z = [
    1,
    'apple',
    2.5,
    ['a', 'b'],
    (1, 2)
]
print(z[0])

1


In [ ]:
# 3.1 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000
a[1] = [1, 2]
print(a)

[10000, [1, 2], 3, 4, 5]


* 문자열은 변경 할 수 없다!

In [ ]:
# 문자열 변경 불가능!!!
s = 'licat'
print(s[0])
s[0] = 'k'                   # 오류 발생

In [ ]:
ss = s.replace("l", "k")
print(ss)

kicat


In [ ]:
# 3.2 리스트 안에 리스트

b = [[10, 20 ,30], [1, 2, 3]]
print(b[1][2])               # 출력: 3


* 다차원 리스트는 헷갈리기 때문에 주의해야한다!'0'

In [ ]:
# 리스트의 덧셈

a = [1, 2, 3]; b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

l = [1, 2, 3]
l = np.array(l)
print(l)
print(l * 3)
print(l + l)

print(type(l))                # ?????ㅜㅜ 몰라 ㅜㅜ

[1 2 3]
[3 6 9]
[2 4 6]
<class 'numpy.ndarray'>


In [ ]:
# numpy 없이 실행하면?
l = [1, 2, 3]

print(1)
print(l * 3)
print(l + l)

print(type(l))                # ?????ㅜㅜ 몰라 ㅜㅜ

1
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3]
<class 'list'>


In [ ]:
# 슬라이싱 실습

l = [1, 2, 3, 4, 5]
print(l[:])
print(l[::-1])
print(l[::2])
print(l[0:4][::-1])         # ?????ㅜㅜ 몰라 ㅜㅜ


[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 3, 5]
[4, 3, 2, 1]


* 데이터가 크다. 내가 원하는대로 데이터를 추출하고 싶다?!\
1.샘풀링-> 1억개 데이터-> 천개-> 리스트 슬라이싱,메서드-> 1억개 데이터에 적용

In [ ]:
# 슬라이싱은 범위를 벗어나도 # 에러가 발생하지 않는다

l = [1, 2, 3, 4, 5]
print(l[10:20])              # ?????ㅜㅜ 몰라 ㅜㅜ

[]
